project:
  type: website
  output-dir: docs


website:
  title: "Kurtis Stefan"
  google-analytics: "UA-263165454-1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Puppers.qmd
        text: Puppers
      - href: Blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true