project:
  type: website
  output-dir: docs


website:
  title: "today"
  google-analytics: "UA-263165454-1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: smokestack.qmd
        text: Smokestack

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true